debug: true

spring:
  thymeleaf:
    cache: false
  datasource:
    #url: 
    username: root
    password: q1w2E#R$

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
